"""
Streamlit live demo: Healthcare Drug Cost & Safety Risk Intelligence.

Reads from a saved data snapshot (data/drug_risk_snapshot.csv), exported
from the Snowflake gold layer + AI explanations. Using a snapshot instead
of a live Snowflake connection means this public app keeps working even
after the Snowflake trial expires -- a deliberate choice for a portfolio
demo, documented in DECISIONS.md.

To refresh with newer data: run export_snapshot.py, then commit the
updated CSV.

Run locally with: streamlit run app.py
"""

import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="Healthcare Drug Cost & Safety Risk",
    layout="wide",
)


@st.cache_data
def load_data():
    return pd.read_csv("data/drug_risk_snapshot.csv")


df = load_data()

# ---------- Header ----------
st.title("Healthcare Drug Cost & Safety Risk Intelligence")
st.caption(
    "Joining real Medicare payment data with real FDA drug recall data to surface "
    "which drugs are simultaneously high-cost-risk and high-safety-risk."
)

# ---------- KPI row ----------
col1, col2, col3, col4 = st.columns(4)
col1.metric("Drugs analyzed", f"{len(df):,}")
col2.metric("High cost-risk", f"{(df['COST_RISK_TIER'] == 'High').sum():,}")
col3.metric("With active recalls", f"{(df['TOTAL_RECALLS'] > 0).sum():,}")
col4.metric("Cumulative billing gap (volume-weighted)", f"${df['DOLLAR_IMPACT'].sum():,.0f}")

st.divider()

# ---------- Filters ----------
st.subheader("Filter")
f_col1, f_col2 = st.columns(2)
with f_col1:
    tier_filter = st.multiselect(
        "Cost risk tier",
        options=sorted(df["COST_RISK_TIER"].dropna().unique()),
        default=sorted(df["COST_RISK_TIER"].dropna().unique()),
    )
with f_col2:
    safety_filter = st.multiselect(
        "Safety risk tier",
        options=sorted(df["SAFETY_RISK_TIER"].dropna().unique()),
        default=sorted(df["SAFETY_RISK_TIER"].dropna().unique()),
    )

filtered = df[
    df["COST_RISK_TIER"].isin(tier_filter)
    & df["SAFETY_RISK_TIER"].isin(safety_filter)
]

st.divider()

# ---------- Chart ----------
st.subheader("Top 15 drugs by combined risk score")
chart_df = filtered.head(15).copy()
# Shorten labels just for the chart's x-axis -- full names are illegible
# rotated vertically. Table and AI explanations below still show full names.
chart_df["short_label"] = chart_df["DRUG_DESC"].str.slice(0, 30) + chart_df["DRUG_DESC"].str.len().gt(30).map({True: "...", False: ""})
chart_data = chart_df.set_index("short_label")["COMBINED_RISK_SCORE"]
st.bar_chart(chart_data)

st.divider()

# ---------- Table ----------
st.subheader("All drugs (filtered)")
st.dataframe(
    filtered[
        ["DRUG_DESC", "PAYMENT_GAP_PCT", "DOLLAR_IMPACT", "TOTAL_RECALLS",
         "SAFETY_RISK_TIER", "COMBINED_RISK_SCORE"]
    ],
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ---------- AI explanations ----------
st.subheader("AI risk explanations — top 10")
st.caption("Generated by an LLM, grounded only in the real numbers shown above for each drug.")

for _, row in filtered.head(10).iterrows():
    with st.expander(f"{row['DRUG_DESC']} — risk score {row['COMBINED_RISK_SCORE']}"):
        if pd.notna(row["AI_EXPLANATION"]):
            st.write(row["AI_EXPLANATION"])
        else:
            st.write("No AI explanation generated for this drug yet.")

st.divider()
st.caption(
    "This demo reads from a periodically-refreshed data snapshot rather than "
    "a live database connection, so it keeps working independent of any "
    "trial/credential lifecycle. In production, this would query Snowflake "
    "directly -- the full pipeline code (Airflow, PySpark, dbt, the AI layer) "
    "is in the GitHub repo linked above."
)
