"""
Streamlit live demo: Healthcare Drug Cost & Safety Risk Intelligence.

Reads directly from Snowflake (gold layer + AI explanations) and shows
an interactive, filterable view of the combined risk analysis.

Run locally with: streamlit run app.py
"""

import streamlit as st
import pandas as pd
import snowflake.connector

from credentials import (
    SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, SNOWFLAKE_PASSWORD,
    SNOWFLAKE_WAREHOUSE, SNOWFLAKE_DATABASE,
)

st.set_page_config(
    page_title="Healthcare Drug Cost & Safety Risk",
    layout="wide",
)


@st.cache_resource
def get_connection():
    return snowflake.connector.connect(
        account=SNOWFLAKE_ACCOUNT,
        user=SNOWFLAKE_USER,
        password=SNOWFLAKE_PASSWORD,
        warehouse=SNOWFLAKE_WAREHOUSE,
        database=SNOWFLAKE_DATABASE,
        schema="gold",
    )


@st.cache_data(ttl=600)
def load_data():
    conn = get_connection()
    query = """
        SELECT
            r.HCPCS_CODE, r.DRUG_DESC, r.TOTAL_SERVICES,
            r.AVG_SUBMITTED_CHARGE, r.AVG_MEDICARE_PAID,
            r.PAYMENT_GAP_PCT, r.DOLLAR_IMPACT, r.COST_RISK_TIER,
            r.TOTAL_RECALLS, r.ONGOING_RECALLS, r.SAFETY_RISK_TIER,
            r.COMBINED_RISK_SCORE,
            e.AI_EXPLANATION
        FROM drug_cost_safety_risk r
        LEFT JOIN drug_risk_explanations e
            ON r.HCPCS_CODE = e.HCPCS_CODE
        ORDER BY r.COMBINED_RISK_SCORE DESC
    """
    cur = conn.cursor()
    cur.execute(query)
    columns = [c[0] for c in cur.description]
    rows = cur.fetchall()
    return pd.DataFrame(rows, columns=columns)


df = load_data()

# ---------- Header ----------
st.title("Healthcare Drug Cost & Safety Risk Intelligence")
st.caption(
    "Joining real Medicare payment data with real FDA drug recall data to surface "
    "which drugs are simultaneously high-cost-risk and high-safety-risk."
)

# ---------- KPI row ----------
col1, col2, col3, col4 = st.columns(4)
col1.metric("Drugs analyzed", f"{len(df):,}")
col2.metric("High cost-risk", f"{(df['COST_RISK_TIER'] == 'High').sum():,}")
col3.metric("With active recalls", f"{(df['TOTAL_RECALLS'] > 0).sum():,}")
col4.metric("Cumulative billing gap (volume-weighted)", f"${df['DOLLAR_IMPACT'].sum():,.0f}")

st.divider()

# ---------- Filters ----------
st.subheader("Filter")
f_col1, f_col2 = st.columns(2)
with f_col1:
    tier_filter = st.multiselect(
        "Cost risk tier",
        options=sorted(df["COST_RISK_TIER"].dropna().unique()),
        default=sorted(df["COST_RISK_TIER"].dropna().unique()),
    )
with f_col2:
    safety_filter = st.multiselect(
        "Safety risk tier",
        options=sorted(df["SAFETY_RISK_TIER"].dropna().unique()),
        default=sorted(df["SAFETY_RISK_TIER"].dropna().unique()),
    )

filtered = df[
    df["COST_RISK_TIER"].isin(tier_filter)
    & df["SAFETY_RISK_TIER"].isin(safety_filter)
]

st.divider()

# ---------- Chart ----------
st.subheader("Top 15 drugs by combined risk score")
chart_df = filtered.head(15).copy()
# Shorten labels just for the chart's x-axis -- full names are illegible
# rotated vertically. Table and AI explanations below still show full names.
chart_df["short_label"] = chart_df["DRUG_DESC"].str.slice(0, 30) + chart_df["DRUG_DESC"].str.len().gt(30).map({True: "...", False: ""})
chart_data = chart_df.set_index("short_label")["COMBINED_RISK_SCORE"]
st.bar_chart(chart_data)

st.divider()

# ---------- Table ----------
st.subheader("All drugs (filtered)")
st.dataframe(
    filtered[
        ["DRUG_DESC", "PAYMENT_GAP_PCT", "DOLLAR_IMPACT", "TOTAL_RECALLS",
         "SAFETY_RISK_TIER", "COMBINED_RISK_SCORE"]
    ],
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ---------- AI explanations ----------
st.subheader("AI risk explanations — top 10")
st.caption("Generated by an LLM, grounded only in the real numbers shown above for each drug.")

for _, row in filtered.head(10).iterrows():
    with st.expander(f"{row['DRUG_DESC']} — risk score {row['COMBINED_RISK_SCORE']}"):
        if pd.notna(row["AI_EXPLANATION"]):
            st.write(row["AI_EXPLANATION"])
        else:
            st.write("No AI explanation generated for this drug yet.")
